### PR TITLE
Chef 17 compatibility & cleanup

### PR DESCRIPTION
**Pull request by detjensrobert**
# Description

Chef 17 requires resources to enable [unified_mode](https://docs.chef.io/unified_mode/) in preparation for Chef 18 when it will be the default mode.

This PR also applies the latest Cookstyle corrections and cleans up the cookbook and testing infrastructure to use modern tools.

## Changes

This PR should have no outward-facing changes.

- Remove Foodcritic (superseded by Cookstyle)
- Enable `unified_mode` for custom resources
- Apply latest Cookstyle fixes
- convert integration tests to InSpec
- Update Travis CI to latest Chef Workstation

### CODE REVIEW

**Comment by detjensrobert** [comment]
@djoos friendly ping to review this when you get a chance :)

**Comment by djoos** [comment]
Thank you for your contribution @detjensrobert - apologies for the delay in getting this merged though!

**Comment by ramereth** [comment]
> Thank you for your contribution @detjensrobert - apologies for the delay in getting this merged though!

@djoos Can you please do a new release to the supermarket which includes this fix? Thanks!

**Comment by ramereth** [comment]
@djoos ping?

**Comment by djoos** [comment]
@ramereth: I've still got a note to address the CHANGELOG.md and version bump (3.0.0 most likely due to the adjustment cutting out EOL Chef versions) and can then push it up.

**Comment by ramereth** [comment]
@djoos any updates on getting this released? Thanks!

**Pull request merged**
